from flask import Flask, request, jsonify

app = Flask(__name__)

faq = {
    "bonjour": "Bonjour ! Comment puis-je vous aider aujourd'hui ?",
    "banjour": "Banjour ! Comment puis-je vous aider aujourd'hui ?",
    "salut": "Salut ! Comment puis-je vous assister ?",
    "hello": "Hello ! En quoi puis-je vous aider ?",
    "coucou": "Coucou ! Que puis-je faire pour vous ?",
    "comment ça va": "Je vais bien, merci ! Et vous ?",
    "j'ai une question": "Bien sûr, je suis là pour vous aider. Quelle est votre question ?",
    "j'ai un problème": "Je suis à votre écoute. Expliquez-moi votre problème.",
    "j'ai besoin d'aide": "Pas de souci, je suis là pour ça. Dites-moi tout.",
    "qui es-tu": "Je suis un chatbot créé pour répondre à vos questions concernant Ooredoo.",
    "quel est ton nom": "Je suis votre assistant virtuel Ooredoo.",
    "merci": "Avec plaisir ! N'hésitez pas si vous avez d'autres questions.",
    "au revoir": "Au revoir et à bientôt !",
    "bye": "Bye bye ! Prenez soin de vous.",
    "quelle heure est-il": "Je suis désolé, je ne peux pas encore donner l'heure ou la date.",
    "quelle est la date": "Je suis désolé, je ne peux pas encore donner la date.",
    "où se trouve ooredoo": "Nos agences sont présentes dans plusieurs villes. Veuillez préciser votre région.",
    "comment contacter le service client": "Vous pouvez appeler le 333 ou visiter notre site officiel pour plus d'informations.",
    "quels sont vos forfaits": "Nous proposons plusieurs forfaits : internet, voix et combos. Consultez notre site pour les détails.",
    "comment recharger mon solde": "Vous pouvez recharger via carte de recharge, application My Ooredoo ou en ligne.",
    "comment activer internet": "Composez *124# et suivez les instructions ou utilisez l'application My Ooredoo.",
    "quel est le numéro du service client": "Vous pouvez contacter le service client Ooredoo au 333.",
    "où est mon agence la plus proche": "Veuillez indiquer votre ville pour que je puisse vous renseigner.",
    "comment activer 4g": "Vous pouvez activer la 4G dans les paramètres réseau de votre téléphone.",
    "comment consulter mon solde": "Composez *111# pour consulter votre solde en temps réel.",
    "comment changer mon forfait": "Contactez le service client ou utilisez l'application My Ooredoo pour changer de forfait.",
    "comment résilier mon forfait": "Veuillez contacter notre service client pour la résiliation de votre forfait.",
    "comment souscrire à une option internet": "Vous pouvez souscrire à une option via l'application My Ooredoo ou en composant le code dédié.",
    "comment savoir mon numéro": "Composez *123# pour connaître votre numéro.",
    "comment activer roaming": "Contactez le service client ou activez le roaming via l'application My Ooredoo.",
    "comment changer de numéro": "Rendez-vous en agence pour changer de numéro ou contactez le service client.",
    "comment activer le contrôle parental": "Activez le contrôle parental via l'application ou demandez assistance au service client.",
    "quel est le prix du forfait internet illimité": "Les tarifs varient, consultez notre site ou contactez le service client pour les détails.",
    "comment recharger via carte bancaire": "Utilisez notre site web ou l'application My Ooredoo pour recharger avec votre carte bancaire.",
    "mon internet ne fonctionne pas": "Essayez de redémarrer votre téléphone ou modem, sinon contactez le support technique.",
    "comment obtenir mon PUK": "Vous pouvez obtenir votre code PUK en contactant le service client.",
    "comment configurer internet sur mon téléphone": "Configurez internet via les paramètres APN disponibles sur notre site.",
    "je veux bloquer mon numéro": "Contactez le service client pour bloquer votre numéro temporairement.",
    "comment payer ma facture": "Payez en ligne, via l'application ou en agence.",
    "comment obtenir un duplicata de facture": "Demandez un duplicata via l'espace client ou en agence.",
    "comment changer mon mot de passe espace client": "Connectez-vous à votre compte et modifiez votre mot de passe dans les paramètres.",
    "où consulter mes factures": "Dans votre espace client ou via l'application My Ooredoo.",
    "comment récupérer mon code puk": "Contactez le service client pour récupérer votre code PUK.",
    "comment annuler une option internet": "Annulez une option via l'application ou en contactant le service client.",
    "mon téléphone est bloqué": "Contactez le service client pour assistance sur le déblocage.",
    "je veux activer VoLTE": "Activez VoLTE dans les paramètres de votre téléphone si compatible.",
    "comment activer VoWiFi": "Activez le WiFi calling dans les paramètres de votre téléphone.",
    "où acheter une carte SIM": "Nos cartes SIM sont disponibles en agence et chez les revendeurs agréés.",
    "combien coûte une carte SIM": "Le prix varie selon l'offre, renseignez-vous en agence ou sur notre site.",
    "mon numéro est bloqué": "Contactez le service client pour débloquer votre numéro.",
    "comment suspendre ma ligne": "Appelez le service client pour suspendre temporairement votre ligne.",
    "comment réactiver ma ligne": "Contactez le service client pour réactiver votre ligne suspendue.",
    "je veux changer mon nom d'utilisateur": "Modifiez votre nom d'utilisateur dans les paramètres de votre espace client.",
    "je veux changer mon mot de passe": "Vous pouvez modifier votre mot de passe via l'espace client.",
    "combien coûte l'option internet journalier": "Consultez nos tarifs en ligne ou via le service client.",
    "quels sont vos forfaits internationaux": "Nous proposons plusieurs forfaits internationaux, disponibles sur notre site.",
    "comment contacter ooredoo via email": "Envoyez un mail à contact@ooredoo.tn (exemple).",
    "est-ce que vous avez une application mobile": "Oui, téléchargez l'application My Ooredoo disponible sur Android et iOS.",
    "comment télécharger l'application My Ooredoo": "Téléchargez-la via Google Play Store ou Apple App Store.",
    "comment consulter mes consommations": "Via l'application ou en composant *111#.",
    "comment activer la messagerie vocale": "Composez le code pour activer la messagerie vocale ou contactez le service client.",
    "comment désactiver la messagerie vocale": "Composez le code pour désactiver la messagerie vocale ou contactez le service client.",
    "comment consulter mes points fidélité": "Consultez vos points via l'application ou l'espace client.",
    "comment utiliser mes points fidélité": "Utilisez-les pour des offres spéciales disponibles dans l'application.",
    "comment parrainer un ami": "Renseignez-vous dans l'application ou contactez le service client.",
    "comment faire un transfert de solde": "Utilisez le code USSD dédié pour transférer du crédit à un proche.",
    "quel est le code pour recharger": "Le code pour recharger est *123*NUMERO_DE_RECHARGE#.",
    "quel est le code pour consulter le solde": "Composez *111# pour consulter votre solde.",
    "mon solde internet est épuisé": "Rechargez votre forfait internet ou souscrivez à une option data.",
    "comment activer Facebook gratuit": "Souscrivez à l’option Facebook via l’application ou le service client.",
    "est-ce que ooredoo propose Netflix": "Nous avons des offres incluant Netflix, consultez notre site pour les détails.",
    "est-ce que je peux payer Netflix avec Ooredoo": "Oui, via votre facture Ooredoo, selon les offres.",
    "est-ce que je peux souscrire à beIN Sport": "Oui, beIN Sport est disponible via certaines offres.",
    "quels sont vos services mobiles": "Nous proposons voix, data, SMS, roaming, et plus.",
    "quels sont vos services fixes": "Internet fixe, téléphonie fixe, fibre optique, TV, etc.",
    "comment souscrire à Ooredoo Fibre": "Contactez le service client ou rendez-vous en agence pour souscrire.",
    "est-ce que vous avez la 5G": "La 5G est en déploiement, renseignez-vous sur les zones couvertes.",
    "comment activer la 5G": "Activez la 5G dans les paramètres réseau de votre téléphone compatible.",
    "mon téléphone est compatible 5G": "Vérifiez les spécifications de votre appareil ou demandez en agence.",
    "combien coûte la fibre optique": "Les tarifs dépendent des offres, consultez notre site pour plus d'informations.",
    "comment demander une installation fibre": "Contactez notre service client ou agence pour planifier l'installation.",
    "mon débit internet est lent": "Vérifiez votre équipement et la couverture, contactez le support si besoin.",
    "comment augmenter mon débit internet": "Contactez le support ou changez d’offre pour plus de débit.",
    "mon wifi ne fonctionne pas": "Redémarrez votre routeur, sinon contactez le support technique.",
    "comment changer mon mot de passe wifi": "Connectez-vous à votre routeur et modifiez le mot de passe dans les paramètres.",
    "comment redémarrer mon routeur": "Débranchez-le, attendez 30 secondes, puis rebranchez-le.",
    "comment configurer mon routeur": "Utilisez le guide fourni avec votre routeur ou contactez le support.",
    "est-ce que ooredoo propose des smartphones": "Oui, nous proposons des smartphones en vente en agence.",
    "où acheter un smartphone chez ooredoo": "En agence ou via notre boutique en ligne.",
    "quels sont les smartphones en promotion": "Consultez les promotions actuelles sur notre site ou en agence.",
    "comment bénéficier des promotions": "Inscrivez-vous à notre newsletter et suivez nos réseaux sociaux.",
    "quels sont vos horaires d’ouverture": "Nos agences ouvrent généralement de 9h à 18h, du lundi au samedi.",
    "êtes-vous ouvert le week-end": "Certaines agences sont ouvertes le samedi, vérifiez l’agence proche de chez vous.",
    "proposez-vous des offres entreprises": "Oui, contactez notre service entreprises pour plus d’informations.",
    "comment contacter le service entreprises": "Appelez le 333 ou visitez la section entreprise sur notre site.",
    "comment récupérer un ancien numéro": "Contactez le service client avec vos informations personnelles.",
    "comment commander une carte SIM en ligne": "Rendez-vous sur notre site officiel pour commander une carte SIM.",
    "comment souscrire à l’offre internet illimité": "Souscrivez via l'application My Ooredoo ou en agence.",
    "comment activer un forfait voix": "Composez le code dédié ou utilisez l’application My Ooredoo.",
    "mon forfait est épuisé": "Rechargez votre forfait ou souscrivez à une option complémentaire.",
    "comment consulter mon historique d’appels": "Disponible dans l’espace client ou via l’application.",
    "comment désactiver une option": "Désactivez une option via l’application ou service client.",
    "comment activer une option": "Activez une option via l’application ou service client.",
    "où trouver mon numéro client": "Dans votre espace client ou sur vos factures.",
    "comment activer Instagram gratuit": "Souscrivez à l’option Instagram gratuite via l’application.",
    "comment obtenir un nouveau modem": "Contactez le service client ou rendez-vous en agence.",
    "mon modem est en panne": "Contactez le support technique pour assistance.",
    "comment vérifier la couverture réseau": "Consultez la carte de couverture sur notre site.",
    "comment activer le double appel": "Activez le double appel dans les paramètres ou via un code USSD.",
    "comment désactiver le double appel": "Désactivez le double appel dans les paramètres ou via un code USSD.",
    "comment souscrire à une assurance téléphone": "Contactez le service client pour plus d’informations.",
    "où trouver les tarifs ooredoo": "Consultez notre site officiel pour tous les tarifs.",
    "comment recevoir sa facture par email": "Activez la facturation électronique dans votre espace client.",
    "comment obtenir un relevé de consommations": "Disponible dans votre espace client ou via l’application.",
    "comment suivre ma commande": "Suivez votre commande via votre espace client ou le lien envoyé par email.",
    "comment modifier mon adresse": "Mettez à jour votre adresse dans l’espace client ou contactez le support.",
    "comment désactiver la 4G": "Désactivez la 4G dans les paramètres réseau de votre téléphone.",
    "comment activer la 3G": "Activez la 3G dans les paramètres réseau de votre téléphone.",
    "comment recharger internet via ticket": "Utilisez le code du ticket de recharge via *123*code#.",
    "comment activer le pack sms": "Souscrivez au pack SMS via l’application ou code USSD.",
    "comment désactiver le pack sms": "Désactivez le pack SMS via l’application ou code USSD.",
    "comment souscrire à TikTok illimité": "Souscrivez via l’application My Ooredoo ou service client.",
    "comment activer WhatsApp gratuit": "Activez l’option WhatsApp gratuite via l’application ou service client.",
    "mon crédit a expiré": "Rechargez pour renouveler la validité de votre crédit.",
    "comment prolonger la validité de mon crédit": "Rechargez ou souscrivez à une option de prolongation.",
    "comment désactiver les notifications SMS": "Désactivez les notifications dans votre espace client.",
    "comment envoyer des SMS à l’international": "Souscrivez à l’option SMS international ou contactez le service client.",
    "comment consulter mon contrat": "Consultez votre contrat dans l’espace client ou demandez une copie en agence.",
    "comment renouveler mon abonnement": "Renouvelez via l’application ou en contactant le service client.",
    "comment changer de forfait sans frais": "Contactez le service client pour connaître les conditions.",
    "comment suspendre internet mobile": "Appelez le service client pour suspendre votre accès internet.",
    "comment récupérer mes contacts SIM": "Utilisez les paramètres de votre téléphone pour importer les contacts SIM.",
    "comment débloquer un téléphone": "Contactez le service client pour obtenir le code de déblocage.",
    "où trouver les conditions générales": "Les conditions générales sont disponibles sur notre site officiel.",
    "comment activer un forfait data": "Activez via l’application ou composez le code dédié.",
    "comment désactiver un forfait data": "Désactivez via l’application ou composez le code dédié.",
    "comment consulter mon solde data": "Composez *111# ou consultez via l’application My Ooredoo.",
    "comment savoir le numéro de mon modem": "Vérifiez l’étiquette de votre modem ou dans son interface d’administration.",
    "comment changer de téléphone": "Rendez-vous en agence ou commandez en ligne un nouveau téléphone.",
    "comment réinitialiser mon modem": "Appuyez sur le bouton reset de votre modem pendant 10 secondes.",
    "comment signaler un problème technique": "Contactez le support technique via le 333 ou l’application.",
    "où trouver un revendeur agréé": "Consultez notre site pour la liste des revendeurs agréés.",
    "quels sont vos packs famille": "Nous proposons plusieurs packs famille, consultez notre site pour les détails.",
    "comment souscrire à un pack famille": "Souscrivez via l’application ou en agence.",
    "quels sont vos packs business": "Des packs business sont disponibles, contactez le service entreprises.",
    "comment souscrire à un pack business": "Contactez le service client entreprises ou rendez-vous en agence.",
    "comment bénéficier d’une remise fidélité": "Les remises sont accordées selon votre ancienneté, renseignez-vous en agence.",
    "comment désactiver internet": "Désactivez internet via l’application ou en composant le code USSD.",
    "comment activer internet mobile": "Activez internet via l’application ou en composant le code USSD.",
    "comment contacter un conseiller": "Appelez le 333 ou utilisez le chat en ligne sur notre site.",
    "comment annuler un abonnement internet": "Contactez le service client pour annuler votre abonnement internet.",
     "comment accéder à l'intranet employé": "Vous pouvez accéder à l'intranet via le portail interne d’Ooredoo.",
    "Comment accéder à l'intranet employé": "Vous pouvez accéder à l'intranet via le portail interne d’Ooredoo.",
    "comment consulter mes fiches de paie": "Vos fiches de paie sont disponibles dans votre espace employé.",
    "Comment consulter mes fiches de paie": "Vos fiches de paie sont disponibles dans votre espace employé.",
    "comment poser un congé": "Connectez-vous à l’intranet et faites une demande via le module RH.",
    "Comment poser un congé": "Connectez-vous à l’intranet et faites une demande via le module RH.",
    "comment modifier mes informations personnelles": "Vous pouvez mettre à jour vos informations via votre espace employé.",
    "Comment modifier mes informations personnelles": "Vous pouvez mettre à jour vos informations via votre espace employé.",
    "où trouver l’organigramme de l’entreprise": "L’organigramme est disponible sur l’intranet dans la section RH.",
    "Où trouver l’organigramme de l’entreprise": "L’organigramme est disponible sur l’intranet dans la section RH.",
    "comment obtenir une attestation de travail": "Faites une demande via le portail RH sur l’intranet.",
    "Comment obtenir une attestation de travail": "Faites une demande via le portail RH sur l’intranet.",
    "comment signaler un problème technique en interne": "Contactez le support IT via le helpdesk interne.",
    "Comment signaler un problème technique en interne": "Contactez le support IT via le helpdesk interne.",
    "comment accéder à ma messagerie professionnelle": "Utilisez l’application Outlook ou via webmail Ooredoo.",
    "Comment accéder à ma messagerie professionnelle": "Utilisez l’application Outlook ou via webmail Ooredoo.",
    "comment réserver une salle de réunion": "Réservez une salle via le calendrier interne ou le portail intranet.",
    "Comment réserver une salle de réunion": "Réservez une salle via le calendrier interne ou le portail intranet.",
    "comment consulter le planning de formation": "Le planning est disponible dans la rubrique Formation sur l’intranet.",
    "Comment consulter le planning de formation": "Le planning est disponible dans la rubrique Formation sur l’intranet.",
    "comment s’inscrire à une formation interne": "Les inscriptions se font via le portail formation de l’intranet.",
    "Comment s’inscrire à une formation interne": "Les inscriptions se font via le portail formation de l’intranet.",
    "comment accéder au guide des procédures internes": "Le guide est disponible dans la documentation interne sur l’intranet.",
    "Comment accéder au guide des procédures internes": "Le guide est disponible dans la documentation interne sur l’intranet.",
    "comment contacter le service RH": "Vous pouvez envoyer un mail à rh@ooredoo.tn ou via l’intranet.",
    "Comment contacter le service RH": "Vous pouvez envoyer un mail à rh@ooredoo.tn ou via l’intranet.",
    "comment consulter les offres de mobilité interne": "Les offres sont publiées sur le portail des opportunités internes.",
    "Comment consulter les offres de mobilité interne": "Les offres sont publiées sur le portail des opportunités internes.",
    "comment activer mon badge d’accès": "Contactez le service sécurité pour l’activation de votre badge.",
    "Comment activer mon badge d’accès": "Contactez le service sécurité pour l’activation de votre badge.",
    "comment signaler une absence": "Prévenez votre manager et faites une déclaration via le module RH.",
    "Comment signaler une absence": "Prévenez votre manager et faites une déclaration via le module RH.",
    "comment demander un télétravail": "La demande de télétravail se fait via l’application RH.",
    "Comment demander un télétravail": "La demande de télétravail se fait via l’application RH.",
    "comment consulter mon solde de congés": "Votre solde de congés est visible dans votre espace RH.",
    "Comment consulter mon solde de congés": "Votre solde de congés est visible dans votre espace RH.",
    "comment accéder à la politique de télétravail": "Elle est disponible sur l’intranet dans la section RH.",
    "Comment accéder à la politique de télétravail": "Elle est disponible sur l’intranet dans la section RH.",
    "où trouver la charte informatique": "La charte est accessible via le portail documentation sur l’intranet.",
    "Où trouver la charte informatique": "La charte est accessible via le portail documentation sur l’intranet.",
    "comment déclarer un accident de travail": "Contactez le service RH et remplissez le formulaire dédié sur l’intranet.",
    "Comment déclarer un accident de travail": "Contactez le service RH et remplissez le formulaire dédié sur l’intranet.",
    "comment consulter mes heures supplémentaires": "Vos heures supplémentaires sont affichées dans votre espace employé.",
    "Comment consulter mes heures supplémentaires": "Vos heures supplémentaires sont affichées dans votre espace employé.",
    "comment obtenir un relevé d’activité": "Demandez-le via le portail RH ou contactez votre manager.",
    "Comment obtenir un relevé d’activité": "Demandez-le via le portail RH ou contactez votre manager.",
    "où trouver le règlement intérieur": "Le règlement intérieur est disponible dans la section documentation RH.",
    "Où trouver le règlement intérieur": "Le règlement intérieur est disponible dans la section documentation RH.",
    "comment signaler un problème de paie": "Envoyez un mail au service paie ou via le formulaire intranet.",
    "Comment signaler un problème de paie": "Envoyez un mail au service paie ou via le formulaire intranet.",
    "comment participer aux événements internes": "Inscrivez-vous via le module événements sur l’intranet.",
    "Comment participer aux événements internes": "Inscrivez-vous via le module événements sur l’intranet.",
    "comment récupérer un document administratif": "Faites la demande via votre espace RH ou contactez l’accueil.",
    "Comment récupérer un document administratif": "Faites la demande via votre espace RH ou contactez l’accueil.",
    "comment faire une demande d’avancement": "Soumettez votre demande via la plateforme RH.",
    "Comment faire une demande d’avancement": "Soumettez votre demande via la plateforme RH.",
    "comment signaler un problème de sécurité": "Contactez le service sécurité via le helpdesk interne.",
    "Comment signaler un problème de sécurité": "Contactez le service sécurité via le helpdesk interne.",
    "comment accéder à la plateforme e-learning": "La plateforme est accessible via l’intranet dans la section Formation.",
    "Comment accéder à la plateforme e-learning": "La plateforme est accessible via l’intranet dans la section Formation."
}

@app.route('/chat', methods=['POST'])
def chat():
    data = request.json
    user_message = data.get('message', '').lower().strip()

    # Cherche si un des mots-clés est présent dans le message utilisateur
    response = None
    for key in faq:
        if key in user_message:
            response = faq[key]
            break

    if response:
        return jsonify({'response': response})
    else:
        return jsonify({'response': "Je n'ai pas compris votre message. Pouvez-vous reformuler ?"})

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)
